export const FORM_ELEMENTS = {
		INPUT: 'INPUT',
		SELECT: 'SELECT',
		TEXT_AREA: 'TEXT_AREA',
		BUTTON: 'BUTTON',
		LABEL: 'LABEL',
		OPTION: 'OPTION',
	}

	export const METHODS = {
		POST: 'POST',
		GET: 'GET',
		PATCH: 'PATCH',
	}

	export const ATTRIBUTES = {
		STYLE: 'STYLE',
		READ_ONLY: 'READ_ONLY',
		PLACEHOLDER: 'PLACEHOLDER',
		VALUE: 'VALUE',
		NAME: 'NAME',
		DISABLED: 'DISABLED',
		SIZE: 'SIZE',
		MIN: 'MIN',
		MAX: 'MAX',
		REQUIRED: 'REQUIRED',
	}

	export const INPUT_TYPES = {
		BUTTON: 'BUTTON',
		CHECKBOX: 'CHECKBOX',
		COLOR: 'COLOR',
		DATE: 'DATE',
		DATETIME_LOCAL: 'DATETIME_LOCAL',
		EMAIL: 'EMAIL',
		FILE: 'FILE',
		HIDDEN: 'HIDDEN',
		IMAGE: 'IMAGE',
		MONTH: 'MONTH',
		NUMBER: 'NUMBER',
		PASSWORD: 'PASSWORD',
		RADIO: 'RADIO',
		RANGE: 'RANGE',
		RESET: 'RESET',
		SEARCH: 'SEARCH',
		SUBMIT: 'SUBMIT',
		TEL: 'TEL',
		TEXT: 'TEXT',
		TIME: 'TIME',
		URL: 'URL',
		WEEK: 'WEEK',
	}

	export const LABEL_POSITIONS = {
		BOTTOM: 'BOTTOM',
		INLINE: 'INLINE',
		TOP: 'TOP',
	}
